replicaCount: 2

image:
  repository: "" # Overridden by CI/CD
  pullPolicy: IfNotPresent
  tag: "latest" # Overridden by CI/CD

service:
  type: ClusterIP
  port: 80
  targetPort: 3002

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

command: ["sh", "-c"]
args: ["npx prisma db push --accept-data-loss && node dist/index.js"]

env:
  - name: PORT
    value: "3002"
  - name: NODE_ENV
    value: "production"
  - name: AWS_REGION
    value: "ap-south-1"
  - name: USE_LOCALSTACK
    value: "false"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: post-database-url
  - name: COGNITO_USER_POOL_ID
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: cognito-user-pool-id
  - name: COGNITO_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: cognito-client-id
  - name: SNS_TOPIC_ARN
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: search-sns-topic-arn
